# 15. Lamba function in Python
* __A Lamba function is a small anonymous function__
* __A lamba function can take any number of arguments but only have one expression__
* __The expression is evaluated and returned__
* __Lamda expression (or lambda function) essentially blocks of code that can be assigned to variable passed as an arguments or returned from a function call , in Language that support high-ordered function__
* __The main role of lambda function is better described in the scenerious when we employ them anonymously inside another functions__
* __In python , the lambda function can be utilized as an arguments to the higher order functions as an arguments__
* __Lambda function in Python__
   * __Syntax__
   * __Normal Function__
   * __Anonymous Function__
  * __Usage__
    * __Lambda with filters__
    * __Lambda with map()__
    * __Lambda with reduce()__
    * __Lambda with apply()__
* __common errors__
   * __Syntax errors__
   * __type Errors__

In [1]:
print("Hello World")

Hello World

In [2]:
x= input("Enter any value:")
y=x+10
print(y)

Enter any value: 32

TypeError: can only concatenate str (not "int") to str

In [4]:
def func1(x):
    return x+6
func1(10)

16

In [5]:
func1(3)

9

In [6]:
(lambda x:x+10)(10)

20

In [7]:
y=(lambda x:x+10)(10)
print(y)

20

In [8]:
y

20

In [9]:
def sqr(a):
    return a**2
sqr(10)

100

In [11]:
(lambda a1:a1**2)(20)

400

In [12]:
import math
def rootNum(y2):
    return math.sqrt(y2)
userVal=int(input("Enter any number:"))    
rootNum(userVal)

Enter any number: 25

5.0

In [15]:
userVal=int(input("Enter any number:"))
(lambda  y2:math.sqrt(y2))(userVal)

Enter any number: 64

8.0

In [3]:
def sumTwo(x,y):
    return x+y
num1=int(input("Enter first number:")) 
num2=int(input("Enter second number:"))
sumTwo(num1,num2)

Enter first number: 12
Enter second number: 32

44

In [5]:
num1=int(input("Enter first number:"))
num2=int(input("Enter second number:"))
(lambda x,y:x+y)(num1,num2)

Enter first number: 21
Enter second number: 21

42

In [6]:
import sys

In [1]:
#help(sys)

In [8]:
import os

In [2]:
#help(os)

In [20]:
arrayList=[1,2,3,4,5,6,7,8,9,10]
newList=[]
oddList=[]
for x in arrayList:
    if x%2==0:
        newList.append(x)
    else:
        oddList.append(x)
print("Even:",newList,type(newList))   
print("Odd:",oddList,type(oddList))

Even: [2, 4, 6, 8, 10] <class 'list'>
Odd: [1, 3, 5, 7, 9] <class 'list'>

In [22]:
#filter
#filter(function,sequence)
arrayList=[1,2,3,4,5,6,7,8,9,10]
list(filter(lambda x:x%2==0,arrayList))

[2, 4, 6, 8, 10]

In [23]:
arrayList=[1,2,3,4,5,6,7,8,9,10]
list(filter(lambda x:x%2!=0,arrayList))

[1, 3, 5, 7, 9]

In [24]:
def sum1():
    x=12
    y=32
    return x+y
sum1()

44

In [25]:
(lambda x,y:x+y)(12,32)

44

In [30]:
weekdays=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]
#print(weekdays)
for i in range(len(weekdays)):
    if len(weekdays[i])>7:
        print(weekdays[i])

Wednesday
Thursday
Saturday

In [33]:
weekdays=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]
list(filter(lambda x1:len(x1)>7,weekdays))

['Wednesday', 'Thursday', 'Saturday']

In [2]:
def sum2(a):
    return 10+a
sum2(23)

33

In [3]:
(lambda a:10+a)(21)

31

In [1]:
fruits = ["Apple","Banana","WaterMelon","CustardApple","CustardApple","DragonFruit","Pineapple","Stawberry"]
print(fruits)
#filter(function,sequence)
i=0
while i<len(fruits):
    #print(fruits[i])
    if len(fruits[i])>10:
        print(fruits[i])
    i+=1

['Apple', 'Banana', 'WaterMelon', 'CustardApple', 'CustardApple', 'DragonFruit', 'Pineapple', 'Stawberry']
CustardApple
CustardApple
DragonFruit

In [4]:
list(filter(lambda x:len(x)>10,fruits))

['CustardApple', 'CustardApple', 'DragonFruit']

In [5]:
def filterFruit(x1):
    if len(x1)>10:
        return x1
filterFruit("Apple")

In [7]:
list(filter(filterFruit,fruits))

['CustardApple', 'CustardApple', 'DragonFruit']

In [10]:
numbers = [10,20,30,40,50,60,-15,-55,-66,-88,100,101]
#filter
def evennum(y):
    if y%2==0:
        return y
evennum(1)

In [14]:
list(filter(lambda y:y%2==0,numbers))

[10, 20, 30, 40, 50, 60, -66, -88, 100]

In [17]:
#positive
def positiveNum(y1):
    if y1>0:
        return y1
positiveNum(-1)

In [19]:
list(filter(lambda y1:y1>0,numbers))

[10, 20, 30, 40, 50, 60, 100, 101]

In [22]:
list(filter(positiveNum,numbers))

[10, 20, 30, 40, 50, 60, 100, 101]

In [38]:
numbers = [10,20,30,40,50,60,-15,-55,-66,-88,100,101]

In [39]:
def negnum(y3):
    if y3<0:
        return y3
negnum(-1)

-1

In [40]:
list(filter(lambda y2:y2<0,numbers))

[-15, -55, -66, -88]

In [41]:
list(filter(negnum,numbers))

[-15, -55, -66, -88]

In [42]:
numbers = [10,20,30,40,50,60,-15,-55,-66,-88,100,101]

In [43]:
def oddnum(y4):
    if y4%2!=0:
        return y4
oddnum(2)

In [44]:
list(filter(lambda y4:y4%2!=0,numbers))

[-15, -55, 101]

In [51]:
tuple(filter(oddnum,numbers))

(-15, -55, 101)

In [46]:
numbers = [10,20,30,40,50,60,-15,-55,-66,-88,100,101]

In [47]:
def div3(s1):
    if s1%3==0:
        return s1
div3(30)

30

In [48]:
list(filter(lambda s2:s2%3==0,numbers))

[30, 60, -15, -66]

In [50]:
tuple(filter(div3,numbers))

(30, 60, -15, -66)

In [64]:
numbers = [10,20,30,40,50,60,-15,-55,-66,-88,100,101]
#numbers greater than 15
def greatnum(s):
    if s>40:
        return s
greatnum(40)

In [65]:
list(filter(lambda s1:s1>15,numbers))

[20, 30, 40, 50, 60, 100, 101]

In [66]:
list(filter(greatnum,numbers))

[50, 60, 100, 101]

In [81]:
list(filter(lambda x2:x2.isalpha() or x2.isnumeric or x2.strip(),string))

['Hello', '', 'World', ' ', 'Python', ' ', '123', ' prasad ']

In [85]:
string = ["Hello","","World",' ',"Python",' ',"123"," prasad "]

def removeSpace(x5):
    x2 = x5.isalpha() or x5.isnumeric() or x5.strip()
    return x2

removeSpace("123")

True

In [4]:
string=["Hello","","World",' ',"Python",' ',"123"," prasad "]

def remove(p):
    p1=p.isalpha() or p.isnumeric() or p.strip()
    return p1
remove(" Hello ")

'Hello'

In [8]:
list(filter(lambda p2:p2.isalpha() or p2.isnumeric() or p2.strip(),string))

['Hello', 'World', 'Python', '123', ' prasad ']

In [10]:
list(filter(remove,string))

['Hello', 'World', 'Python', '123', ' prasad ']

In [4]:
numbers = [10,20,30,40,50,60,-15,-55,-66,-88,100,101]
#lambda with map()
def sqrNum(s):
    return s**2
sqrNum(2)

4

In [5]:
list(filter(lambda s1:s1**2,numbers))

[10, 20, 30, 40, 50, 60, -15, -55, -66, -88, 100, 101]

In [6]:
tuple(map(lambda s:s**2,numbers))

(100, 400, 900, 1600, 2500, 3600, 225, 3025, 4356, 7744, 10000, 10201)

In [7]:
list(map(lambda s:s**2,numbers))

[100, 400, 900, 1600, 2500, 3600, 225, 3025, 4356, 7744, 10000, 10201]

In [9]:
list(map(sqrNum,numbers))

[100, 400, 900, 1600, 2500, 3600, 225, 3025, 4356, 7744, 10000, 10201]

In [25]:
#table of 3
table=[1,2,3,4,5,6,7,8,9,10]
def table3(b):
    return b*3
table3(4)

12

In [28]:
list(map(lambda b1:b1*3,table))

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30]

In [29]:
list(map(table3,table))

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30]

In [1]:
#lambda with reduce()
from functools import reduce

In [2]:
#help(reduce)

In [3]:
#number series
list2=[3, 6, 9, 12, 15, 18, 21, 24, 27, 30]
def redTwo(x,y):
    return x*y
redTwo(3,6)

18

In [4]:
reduce(redTwo,list2)

214277011200

In [5]:
reduce(lambda a,b:a+b,list2)

165

In [6]:
reduce(lambda a,b:a-b,list2)

-159

In [7]:
reduce(lambda a,b:a/b,list2)

4.200170587408306e-11

In [8]:
reduce(lambda a,b:a%b,list2)

3

In [14]:
reduce(lambda a,b:a>b,list2)

False

In [15]:
reduce(lambda a,b:a<b,list2)

True

In [20]:
#lambda with apply()
from pandas import pandas
import pandas as pd

In [21]:
x = [[1,2,3,4,9],[5,6,7,8,10],[11,12,13,14,15]]
print(x)

[[1, 2, 3, 4, 9], [5, 6, 7, 8, 10], [11, 12, 13, 14, 15]]

In [22]:
df = pd.DataFrame(x)
df

    0   1   2   3   4
0   1   2   3   4   9
1   5   6   7   8  10
2  11  12  13  14  15

In [23]:
df.shape

(3, 5)

In [24]:
df.size

15

In [25]:
type(df)

pandas.core.frame.DataFrame

In [26]:
data=df[4][0]
data

np.int64(9)

In [27]:
df=pd.DataFrame(x)

In [28]:
df1 = df[4][0]
print(df1)

9

In [29]:
for i in df:
    print(df[i]**2)

0      1
1     25
2    121
Name: 0, dtype: int64
0      4
1     36
2    144
Name: 1, dtype: int64
0      9
1     49
2    169
Name: 2, dtype: int64
0     16
1     64
2    196
Name: 3, dtype: int64
0     81
1    100
2    225
Name: 4, dtype: int64

In [30]:
df

    0   1   2   3   4
0   1   2   3   4   9
1   5   6   7   8  10
2  11  12  13  14  15

In [31]:
df5= df.apply(lambda y:y**2)
df5

     0    1    2    3    4
0    1    4    9   16   81
1   25   36   49   64  100
2  121  144  169  196  225

In [32]:
df3 = df[4][0]
df3

np.int64(9)

In [33]:
#TypeError
df3= df.apply(lambda x,y:x+y)

TypeError: <lambda>() missing 1 required positional argument: 'y'

In [34]:
#SyntaxError
df3= df.apply(lambda x,)

SyntaxError: invalid syntax (3575773480.py, line 2)